// Code generated by ent, DO NOT EDIT.

package vote

import (
	"poll-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldID, id))
}

// UserId applies equality check predicate on the "userId" field. It's identical to UserIdEQ.
func UserId(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldUserId, v))
}

// PollOptionId applies equality check predicate on the "pollOptionId" field. It's identical to PollOptionIdEQ.
func PollOptionId(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldPollOptionId, v))
}

// UserIdEQ applies the EQ predicate on the "userId" field.
func UserIdEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldUserId, v))
}

// UserIdNEQ applies the NEQ predicate on the "userId" field.
func UserIdNEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldUserId, v))
}

// UserIdIn applies the In predicate on the "userId" field.
func UserIdIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldUserId, vs...))
}

// UserIdNotIn applies the NotIn predicate on the "userId" field.
func UserIdNotIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldUserId, vs...))
}

// UserIdGT applies the GT predicate on the "userId" field.
func UserIdGT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldUserId, v))
}

// UserIdGTE applies the GTE predicate on the "userId" field.
func UserIdGTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldUserId, v))
}

// UserIdLT applies the LT predicate on the "userId" field.
func UserIdLT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldUserId, v))
}

// UserIdLTE applies the LTE predicate on the "userId" field.
func UserIdLTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldUserId, v))
}

// UserIdContains applies the Contains predicate on the "userId" field.
func UserIdContains(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContains(FieldUserId, v))
}

// UserIdHasPrefix applies the HasPrefix predicate on the "userId" field.
func UserIdHasPrefix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasPrefix(FieldUserId, v))
}

// UserIdHasSuffix applies the HasSuffix predicate on the "userId" field.
func UserIdHasSuffix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasSuffix(FieldUserId, v))
}

// UserIdEqualFold applies the EqualFold predicate on the "userId" field.
func UserIdEqualFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEqualFold(FieldUserId, v))
}

// UserIdContainsFold applies the ContainsFold predicate on the "userId" field.
func UserIdContainsFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContainsFold(FieldUserId, v))
}

// PollOptionIdEQ applies the EQ predicate on the "pollOptionId" field.
func PollOptionIdEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEQ(FieldPollOptionId, v))
}

// PollOptionIdNEQ applies the NEQ predicate on the "pollOptionId" field.
func PollOptionIdNEQ(v string) predicate.Vote {
	return predicate.Vote(sql.FieldNEQ(FieldPollOptionId, v))
}

// PollOptionIdIn applies the In predicate on the "pollOptionId" field.
func PollOptionIdIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldIn(FieldPollOptionId, vs...))
}

// PollOptionIdNotIn applies the NotIn predicate on the "pollOptionId" field.
func PollOptionIdNotIn(vs ...string) predicate.Vote {
	return predicate.Vote(sql.FieldNotIn(FieldPollOptionId, vs...))
}

// PollOptionIdGT applies the GT predicate on the "pollOptionId" field.
func PollOptionIdGT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGT(FieldPollOptionId, v))
}

// PollOptionIdGTE applies the GTE predicate on the "pollOptionId" field.
func PollOptionIdGTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldGTE(FieldPollOptionId, v))
}

// PollOptionIdLT applies the LT predicate on the "pollOptionId" field.
func PollOptionIdLT(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLT(FieldPollOptionId, v))
}

// PollOptionIdLTE applies the LTE predicate on the "pollOptionId" field.
func PollOptionIdLTE(v string) predicate.Vote {
	return predicate.Vote(sql.FieldLTE(FieldPollOptionId, v))
}

// PollOptionIdContains applies the Contains predicate on the "pollOptionId" field.
func PollOptionIdContains(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContains(FieldPollOptionId, v))
}

// PollOptionIdHasPrefix applies the HasPrefix predicate on the "pollOptionId" field.
func PollOptionIdHasPrefix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasPrefix(FieldPollOptionId, v))
}

// PollOptionIdHasSuffix applies the HasSuffix predicate on the "pollOptionId" field.
func PollOptionIdHasSuffix(v string) predicate.Vote {
	return predicate.Vote(sql.FieldHasSuffix(FieldPollOptionId, v))
}

// PollOptionIdEqualFold applies the EqualFold predicate on the "pollOptionId" field.
func PollOptionIdEqualFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldEqualFold(FieldPollOptionId, v))
}

// PollOptionIdContainsFold applies the ContainsFold predicate on the "pollOptionId" field.
func PollOptionIdContainsFold(v string) predicate.Vote {
	return predicate.Vote(sql.FieldContainsFold(FieldPollOptionId, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Vote) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Vote) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Vote) predicate.Vote {
	return predicate.Vote(func(s *sql.Selector) {
		p(s.Not())
	})
}
