// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"poll-app/ent/poll"
	"poll-app/ent/polloption"
	"poll-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PollOptionUpdate is the builder for updating PollOption entities.
type PollOptionUpdate struct {
	config
	hooks    []Hook
	mutation *PollOptionMutation
}

// Where appends a list predicates to the PollOptionUpdate builder.
func (pou *PollOptionUpdate) Where(ps ...predicate.PollOption) *PollOptionUpdate {
	pou.mutation.Where(ps...)
	return pou
}

// SetOption sets the "option" field.
func (pou *PollOptionUpdate) SetOption(s string) *PollOptionUpdate {
	pou.mutation.SetOption(s)
	return pou
}

// AddPollIDs adds the "poll" edge to the Poll entity by IDs.
func (pou *PollOptionUpdate) AddPollIDs(ids ...int) *PollOptionUpdate {
	pou.mutation.AddPollIDs(ids...)
	return pou
}

// AddPoll adds the "poll" edges to the Poll entity.
func (pou *PollOptionUpdate) AddPoll(p ...*Poll) *PollOptionUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pou.AddPollIDs(ids...)
}

// Mutation returns the PollOptionMutation object of the builder.
func (pou *PollOptionUpdate) Mutation() *PollOptionMutation {
	return pou.mutation
}

// ClearPoll clears all "poll" edges to the Poll entity.
func (pou *PollOptionUpdate) ClearPoll() *PollOptionUpdate {
	pou.mutation.ClearPoll()
	return pou
}

// RemovePollIDs removes the "poll" edge to Poll entities by IDs.
func (pou *PollOptionUpdate) RemovePollIDs(ids ...int) *PollOptionUpdate {
	pou.mutation.RemovePollIDs(ids...)
	return pou
}

// RemovePoll removes "poll" edges to Poll entities.
func (pou *PollOptionUpdate) RemovePoll(p ...*Poll) *PollOptionUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pou.RemovePollIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pou *PollOptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pou.sqlSave, pou.mutation, pou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pou *PollOptionUpdate) SaveX(ctx context.Context) int {
	affected, err := pou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pou *PollOptionUpdate) Exec(ctx context.Context) error {
	_, err := pou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pou *PollOptionUpdate) ExecX(ctx context.Context) {
	if err := pou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pou *PollOptionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(polloption.Table, polloption.Columns, sqlgraph.NewFieldSpec(polloption.FieldID, field.TypeInt))
	if ps := pou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pou.mutation.Option(); ok {
		_spec.SetField(polloption.FieldOption, field.TypeString, value)
	}
	if pou.mutation.PollCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: polloption.PollPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.RemovedPollIDs(); len(nodes) > 0 && !pou.mutation.PollCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: polloption.PollPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: polloption.PollPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{polloption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pou.mutation.done = true
	return n, nil
}

// PollOptionUpdateOne is the builder for updating a single PollOption entity.
type PollOptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PollOptionMutation
}

// SetOption sets the "option" field.
func (pouo *PollOptionUpdateOne) SetOption(s string) *PollOptionUpdateOne {
	pouo.mutation.SetOption(s)
	return pouo
}

// AddPollIDs adds the "poll" edge to the Poll entity by IDs.
func (pouo *PollOptionUpdateOne) AddPollIDs(ids ...int) *PollOptionUpdateOne {
	pouo.mutation.AddPollIDs(ids...)
	return pouo
}

// AddPoll adds the "poll" edges to the Poll entity.
func (pouo *PollOptionUpdateOne) AddPoll(p ...*Poll) *PollOptionUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pouo.AddPollIDs(ids...)
}

// Mutation returns the PollOptionMutation object of the builder.
func (pouo *PollOptionUpdateOne) Mutation() *PollOptionMutation {
	return pouo.mutation
}

// ClearPoll clears all "poll" edges to the Poll entity.
func (pouo *PollOptionUpdateOne) ClearPoll() *PollOptionUpdateOne {
	pouo.mutation.ClearPoll()
	return pouo
}

// RemovePollIDs removes the "poll" edge to Poll entities by IDs.
func (pouo *PollOptionUpdateOne) RemovePollIDs(ids ...int) *PollOptionUpdateOne {
	pouo.mutation.RemovePollIDs(ids...)
	return pouo
}

// RemovePoll removes "poll" edges to Poll entities.
func (pouo *PollOptionUpdateOne) RemovePoll(p ...*Poll) *PollOptionUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pouo.RemovePollIDs(ids...)
}

// Where appends a list predicates to the PollOptionUpdate builder.
func (pouo *PollOptionUpdateOne) Where(ps ...predicate.PollOption) *PollOptionUpdateOne {
	pouo.mutation.Where(ps...)
	return pouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pouo *PollOptionUpdateOne) Select(field string, fields ...string) *PollOptionUpdateOne {
	pouo.fields = append([]string{field}, fields...)
	return pouo
}

// Save executes the query and returns the updated PollOption entity.
func (pouo *PollOptionUpdateOne) Save(ctx context.Context) (*PollOption, error) {
	return withHooks(ctx, pouo.sqlSave, pouo.mutation, pouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pouo *PollOptionUpdateOne) SaveX(ctx context.Context) *PollOption {
	node, err := pouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pouo *PollOptionUpdateOne) Exec(ctx context.Context) error {
	_, err := pouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pouo *PollOptionUpdateOne) ExecX(ctx context.Context) {
	if err := pouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pouo *PollOptionUpdateOne) sqlSave(ctx context.Context) (_node *PollOption, err error) {
	_spec := sqlgraph.NewUpdateSpec(polloption.Table, polloption.Columns, sqlgraph.NewFieldSpec(polloption.FieldID, field.TypeInt))
	id, ok := pouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PollOption.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, polloption.FieldID)
		for _, f := range fields {
			if !polloption.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != polloption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pouo.mutation.Option(); ok {
		_spec.SetField(polloption.FieldOption, field.TypeString, value)
	}
	if pouo.mutation.PollCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: polloption.PollPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.RemovedPollIDs(); len(nodes) > 0 && !pouo.mutation.PollCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: polloption.PollPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: polloption.PollPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PollOption{config: pouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{polloption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pouo.mutation.done = true
	return _node, nil
}
